Todo/Todo/Controllers/SessionController.cs
using System.Web.Mvc;
using AbstractConfigurationManager;
using ServiceInterfaces;
using Logging;
using Todo.Models.Users;

namespace Todo.Controllers
{
    public class SessionController : SessionBaseController
    {
        private readonly IUserService _userService;

        public SessionController(IUserService userService, IConfigurationManager configurationManager, ILogger logger)
            : base(configurationManager, logger)
        {
            _userService = userService;
        }

        public ActionResult New(string redirectTo)
        {
            if (_userService.GetRegisteredUser() == null)
            {
                TempData["message"] = "User does not exist";
                return RedirectToAction("New", "User");
            }
            return View(new LogonViewModel { RedirectTo = redirectTo });
        }

        public ActionResult Create(LogonViewModel user)
        {
            Logger.Info(string.Format("User Name: {0}; Password {1}", user.UserName, user.Password));
            if (ModelState.IsValid)
            {
                var isUser =
                    _userService.Logon(user.UserName, user.Password);

                if (isUser)
                {
                    TempData["message"] = "User logged on";
                    CreateCookie(user.UserName);
                    return string.IsNullOrEmpty(user.RedirectTo)
                               ? RedirectToAction("Index", "Home", null)
                               : Redirect(user.RedirectTo) as ActionResult;
                }
                Logger.Info("User failed to login.");
            }
            TempData["message"] = "Unable to log user on";
            return View("New", user);
        }

        public ActionResult Delete()
        {
            CreateCookie("", -10);
            TempData["message"] = "Session ended";
            return RedirectToAction("New");
        }
    }
}

Todo/Todo/Views/Session/New.cshtml
@model Todo.Models.Users.LogonViewModel
@{
    ViewBag.Title = "Sign in to Itsa";
    Layout = "~/Views/Shared/_LayoutNoSession.cshtml";
}

<div id="session-index">
    <div id="login-page-container">
        <div id="login-page-liner">
            <div id="introduction-container">
                <div id="login-container">

                    <h2>Sign in</h2>
                    @using (Html.BeginForm("Create", "Session"))
                    {
                        @Html.LabelFor(m => m.UserName) @: @Html.TextBoxFor(m => m.UserName, new { @class = "text-box single-line", autocomplete = "off" })@Html.ValidationMessageFor(m => m.UserName, "*")
                        @Html.LabelFor(m => m.Password) @: @Html.PasswordFor(m => m.Password)  @Html.ValidationMessageFor(m => m.Password, "*")<br/>
                        @Html.HiddenFor(m => m.RedirectTo)
                        <input id="signin" type="submit" value="Sign in" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        var redirectToField = $('#RedirectTo');
        redirectToField.val(redirectToField.val() + window.location.hash);
    });
</script>

<script>
    $("#userName,#Password").focus(function () {
        $(this).addClass("focus");
    }).blur(function () {
        $(this).removeClass("focus");
    });
    $("#signin").hover(function () {
        $(this).addClass("hover");
    }, function () {
        $(this).removeClass("hover");
    });
</script>